### ISSUE TITLE
Disabled buttons make the transcript don't work

### ISSUE THREAD

**Issue by Just1diaxx** [FroostySnoowman/py-discord-html-transcripts#1]
Console log:
`Traceback (most recent call last):
  File "/home/container/.local/lib/python3.12/site-packages/chat_exporter/construct/transcript.py", line 161, in export
    return await super().build_transcript()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/chat_exporter/construct/transcript.py", line 53, in build_transcript
    message_html, meta_data = await gather_messages(
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/chat_exporter/construct/message.py", line 451, in gather_messages
    content_html, meta_data = await MessageConstruct(
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/chat_exporter/construct/message.py", line 89, in construct_message
    await self.build_message()
  File "/home/container/.local/lib/python3.12/site-packages/chat_exporter/construct/message.py", line 95, in build_message
    await self.build_interaction()
  File "/home/container/.local/lib/python3.12/site-packages/chat_exporter/construct/message.py", line 219, in build_interaction
    ("COMMAND", "/" + self.message.interaction_metadata.name, PARSE_MODE_NONE),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MessageInteractionMetadata' object has no attribute 'name'`

**Comment by FroostySnoowman** [comment]
Are you on the latest version of Discord.py? This only works on the very latest version. Otherwise, use one version below on PyPI. (pip install py-discord-html-transcripts==1.0.1)

**Comment by Just1diaxx** [comment]
Yes, with my hosting every library updates at every restart.

**Comment by FroostySnoowman** [comment]
Please tell me the version you're using

**Comment by Just1diaxx** [comment]
> Please tell me the version you're using

discord.py 2.3.2
py-discord-html-transcripts 1.0.4

**Comment by FroostySnoowman** [comment]
That is not the latest version of discord.py. Please downgrade the transcripts library or alternatively, upgrade to 2.4.0 discord.py. https://pypi.org/project/discord.py/

**Comment by Just1diaxx** [comment]
![IMG_20240729_085446589.jpg](https://github.com/user-attachments/assets/5e097f5d-17bc-4e05-b371-fd7ddd7bf31d)

Same thing.

**Comment by Just1diaxx** [comment]
![image](https://github.com/user-attachments/assets/e8eef51b-bb2d-457a-8661-af9c6ef6231d)
Same thing

**Comment by Just1diaxx** [comment]
I updated to 2.4.0 and downgraded transcripts to 1.0.1

**Comment by FroostySnoowman** [comment]
Use the latest version of transcripts...

**Comment by Just1diaxx** [comment]
> Use the latest version of transcripts... 

Same thing

**Comment by FroostySnoowman** [comment]
Apologies for the delay. I have just tested it, and it works fine. Please resend your discord.py and transcripts versions. Alongside this, make sure you have just "discord.py" installed, not "discord" as well.

**Comment by FroostySnoowman** [comment]
Hello, are you still facing this issue? If we don't hear back, we will close this due to inactivity.

**Comment by Just1diaxx** [comment]
No, i just updated the transcripts  and discord.py to the latest version

**Comment by FroostySnoowman** [comment]
Could you please type `pip freeze` into a command prompt/terminal and send that output here?

**Comment by FroostySnoowman** [comment]
<img width="1326" alt="Screenshot 2024-08-15 at 2 44 01 PM" src="https://github.com/user-attachments/assets/88123ece-1138-49cc-ac5a-84673826b2a2">
As a "proof" or whatever you would like to call it, here it is working. A disabled button.

**Comment by FroostySnoowman** [comment]
Hello, after extensive experimenting, the issue is not relating to a disabled button, but rather a slash command inside of the channel in which you want to create the transcript in. I will be pushing an update here shortly.

**Comment by FroostySnoowman** [comment]
It should now be fixed. Thanks to Discord, we can't access the actual slash command name anymore.

**Comment by FroostySnoowman** [comment]
Just following up, have you had a chance to test this?

**Comment by FroostySnoowman** [comment]
Closed due to inactivity.
